---
# Schema for agentic tools rule generation

source_files:
  - name: vital.md
    cursor_rule: rules-vital.mdc
    description: Enhanced development standards with automated quality gates and modern tooling
    always_apply: true
  - name: author.md
    cursor_rule: rules-author.mdc
    description: AI documentation assistant guidelines for generating high-quality, actionable documentation
    always_apply: false
  - name: lotr-data.md
    cursor_rule: rules-lotr-data.mdc
    description: Lord of the Rings reference data for mock data, test users, and environment names
    always_apply: false
  - name: wow-data.md
    cursor_rule: rules-wow-data.mdc
    description: World of Warcraft reference data for mock data, test users, and environment names
    always_apply: false
  - name: shell-styles.md
    cursor_rule: rules-shell-styles.mdc
    description: Shell script style guide with best practices and standards
    always_apply: false
  - name: python-styles.md
    cursor_rule: rules-python-styles.mdc
    description: Python style guide with type safety, testing, and security standards
    always_apply: false

tools:
  claude:
    output_file: CLAUDE.md
    description: Core development standards with concrete examples and actionable guidance
    always_apply: true
  cursor:
    rules_dir: .cursor/rules
    individual_files: true
